# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b8dba4badd496b8e2ac1317b8a1eedeb9f848bedb82dcd087c5b028e97b78103e2394df1ea91294e7dbfd6ffa3dca67bd3bb7b35c10fed5768f73ee9e4893a1

test:
  secret_key_base: ecaaf04201826d594b30b1d59d6816ab7706bb41f8b680273bb0d855878ba35946ed3fc1a8c4b0e0d0dffcde5095f8a06eb4a003100d0479a7be76a437c83748

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
